<script setup lang="ts">
import '@m3e/web/form-field';
import '@m3e/web/icon-button';
import '@m3e/web/icon';
import { nextTick, ref, useTemplateRef } from 'vue';
import { generateContent } from '@/utils/prompt';
import '@m3e/web/dialog';
import { M3eDialogElement } from '@m3e/web/dialog';
import { parse } from 'marked';
import DOMPurify from 'dompurify';

const currentUserInput = ref<string>('');
const downloaded = ref<number>(0);
const downloadDialog = useTemplateRef<M3eDialogElement>('downloadDialog');
const messageResponses = ref<LanguageModelMessage[]>([]);
const chatAreaRef = useTemplateRef<HTMLDivElement>('chatArea');

let dialogOpened: boolean = false;

async function onMessageSend() {
	const message = currentUserInput.value;
	console.log('Message sent:', message);

	currentUserInput.value = '';

	scrollToBottom();

	messageResponses.value.push({ role: 'user', content: message });
	messageResponses.value.push({ role: 'assistant', content: '' });

	let response = '';

	try {
		response = await generateContent(
			message,
			messageResponses.value,
			async (loaded) => {
				downloaded.value = loaded;
				if (!dialogOpened && loaded !== 0 && loaded !== 1) {
					await downloadDialog.value?.show();
					dialogOpened = true;
				}
			},
			(message) => {
				messageResponses.value[messageResponses.value.length - 1]!.content = message;
			},
			async (chunk) => {
				response += chunk;
				messageResponses.value[messageResponses.value.length - 1]!.content = await parseRawResponse(response);
				scrollToBottom();
			},
		);

		messageResponses.value[messageResponses.value.length - 1]!.content = await parseRawResponse(response);
	} catch (error) {
		messageResponses.value[messageResponses.value.length - 1]!.content = `${error}`;
	}
}

async function parseRawResponse(response: string): Promise<string> {
	const parsed = await parse(response);
	return DOMPurify.sanitize(parsed);
}

async function scrollToBottom() {
	if (!chatAreaRef.value) return;

	await nextTick();

	const isNearBottom = chatAreaRef.value.scrollHeight - chatAreaRef.value.scrollTop <= chatAreaRef.value.clientHeight + 100;
	if (!isNearBottom) return;

	chatAreaRef.value.scrollTo({
		top: chatAreaRef.value.scrollHeight,
		behavior: 'smooth',
	});
}
</script>

<template>
	<div class="chat-wrapper">
		<div class="chat-header">
			<p class="chat-header-title">Chrome Built-in AI Demo</p>
		</div>
		<div ref="chatArea" class="chat-area">
			<div v-for="(conversationItem, index) in messageResponses" :key="index" :class="conversationItem.role === 'user' ? 'conv-right' : 'conv-left'" v-html="conversationItem.content"></div>
		</div>
		<div class="chatbar">
			<m3e-form-field variant="outlined" class="chat-input">
				<label slot="label" for="chat-fld">Message Gemini Nano</label>
				<input v-model="currentUserInput" id="chat-fld" @change="onMessageSend()" />
				<span slot="hint">Content generated by Gemini Nano is generated locally. Gemini Nano is AI and can make mistakes.</span>
			</m3e-form-field>
			<m3e-icon-button variant="filled" class="send-button" @click="onMessageSend()">
				<m3e-icon name="send"></m3e-icon>
			</m3e-icon-button>
		</div>
		<m3e-dialog ref="downloadDialog" id="download-dlg" disable-close>
			<span slot="header">Downloading model ({{ downloaded * 100 }}%)</span>
			<p>Please wait while the model is downloading.</p>
		</m3e-dialog>
	</div>
</template>

<style scoped>
.chat-wrapper {
	width: 100dvw;
	height: 100dvh;
	display: flex;
	flex-direction: column;
	box-sizing: border-box;
}

.chatbar {
	display: flex;
	flex-direction: row;
	align-items: center;
	justify-content: center;
	padding: 20px;
	gap: 20px;
	background-color: var(--md-sys-color-surface-container);
	color: var(--md-sys-color-on-surface-container);
	width: 100%;
	height: fit-content;
	flex-shrink: 0;
	box-sizing: border-box;
	border-radius: 25px 25px 0 0;
}

.chat-area {
	flex-grow: 1;
	box-sizing: border-box;
	overflow-y: scroll;
	display: flex;
	flex-direction: column;
	justify-content: flex-start;
	padding: 20px;
}

.chat-header {
	flex-shrink: 0;
	display: flex;
	flex-direction: row;
	align-items: center;
	justify-content: flex-start;
	gap: 20px;
	padding: 20px;
	background-color: var(--md-sys-color-surface-container);
	color: var(--md-sys-color-on-surface-container);
	width: 100%;
	box-sizing: border-box;
	height: fit-content;
	border-radius: 0 0 25px 25px;
}

.chat-header-title {
	font-size: 1.2rem;
}

.chat-input {
	flex-grow: 9;
	margin: 0;
}

.send-button {
	flex-grow: 1;
}

.conv-right,
.conv-left {
	width: fit-content;
	max-width: 80%;
	margin: 20px;
	padding: 10px;
	box-sizing: border-box;
	border-radius: 25px;
}

.conv-right {
	text-align: right;
	align-self: flex-end;
	background-color: var(--md-sys-color-primary-container);
	color: var(--md-sys-color-on-primary-container);
}

.conv-left {
	text-align: left;
	align-self: flex-start;
	background-color: var(--md-sys-color-secondary-container);
	color: var(--md-sys-color-on-secondary-container);
}
</style>
